name: "Genmon"
description: "Genmon generator monitoring app"
version: "0.1.1"
slug: "genmon"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ingress: true
ingress_port: 8000
discovery: 
  - mqtt